Repository nikako-ne-propustiti/blurr, pull requests merged in 2022-05, with the labels that each got.

#77 Backend za korisnike i pregled objava
  backend/Gemfile
  backend/Gemfile.lock
  backend/app/controllers/accounts_controller.rb
  backend/app/controllers/application_controller.rb
  backend/app/controllers/review_controller.rb
  backend/app/controllers/static_controller.rb
  backend/app/models/block.rb
  backend/app/models/comment.rb
  backend/app/models/comment_like.rb
  backend/app/models/follow.rb
  backend/app/models/hashtag.rb
  backend/app/models/post.rb
  backend/app/models/post_like.rb
  backend/app/models/unlock.rb
  backend/app/models/user.rb
  backend/config/application.rb
  backend/config/routes.rb
  backend/db/schema.rb
  backend/test/fixtures/blocks.yml
  backend/test/fixtures/comment_likes.yml
  backend/test/fixtures/comments.yml
  backend/test/fixtures/follows.yml
  backend/test/fixtures/hashtags.yml
  backend/test/fixtures/post_likes.yml
  backend/test/fixtures/posts.yml
  backend/test/fixtures/unlocks.yml
  backend/test/fixtures/users.yml
  frontend/src/api/base.ts
Labels: enhancement

#79 Uklonjeni kompozitni primarni ključevi
  backend/config/application.rb
  backend/db/schema.rb
  frontend/src/api/index.ts
  frontend/src/api/logout.ts
  frontend/src/shared/Context.tsx
  frontend/src/wrapper/Navbar.tsx
Labels: bug

#78 Backend za korisničku stranu, izlistavanje objava i praćenje
  README.md
  backend/app/controllers/accounts_controller.rb
  backend/app/controllers/application_controller.rb
  backend/app/controllers/posts_controller.rb
  backend/app/controllers/users_controller.rb
  backend/app/models/follow.rb
  backend/app/models/post.rb
  backend/app/models/user.rb
  backend/config/routes.rb
  frontend/src/api/accountinfo.ts
  frontend/src/api/base.ts
  frontend/src/api/follow.ts
  frontend/src/api/getSuggestions.ts
  frontend/src/api/index.ts
  frontend/src/api/posts.ts
  frontend/src/api/profilePhoto.ts
  frontend/src/models/Post.ts
  frontend/src/models/PostBasicInfo.ts
  frontend/src/models/User.ts
  frontend/src/routes/accounts/FollowSuggestions.css
  frontend/src/routes/accounts/FollowSuggestions.tsx
  frontend/src/routes/accounts/ProfilePhoto.tsx
  frontend/src/routes/posts/PostGrid.tsx
  frontend/src/routes/posts/PostPreview.tsx
  frontend/src/routes/posts/ViewFeed.tsx
  frontend/src/routes/posts/ViewPost.tsx
  frontend/src/routes/posts/ViewUserFeed.tsx
Labels: enhancement

#92 Profilne slike
  backend/app/assets/images/.keep
  backend/app/assets/images/default_user.jpg
  backend/app/controllers/posts_controller.rb
  backend/app/controllers/users_controller.rb
  backend/app/models/user.rb
  backend/config/routes.rb
  docker-compose.yml
  frontend/src/api/base.ts
  frontend/src/api/index.ts
  frontend/src/routes/accounts/FollowSuggestions.tsx
  frontend/src/routes/accounts/ProfilePhoto.tsx
  frontend/src/routes/posts/ViewUserFeed.tsx
Labels: enhancement

#93 Seed-ovanje baze podataka
  backend/app/models/block.rb
  backend/app/models/comment.rb
  backend/db/seeds.rb
Labels: enhancement

#95 Various bugfixes
  Dockerfile
  backend/app/controllers/accounts_controller.rb
  backend/app/controllers/posts_controller.rb
  backend/app/controllers/users_controller.rb
  backend/app/models/comment.rb
  backend/app/models/post.rb
  backend/app/models/user.rb
  backend/config/application.rb
  backend/config/routes.rb
  frontend/src/App.tsx
  frontend/src/api/accountinfo.ts
  frontend/src/api/createComment.ts
  frontend/src/api/deletePost.ts
  frontend/src/api/editAccount.ts
  frontend/src/api/index.ts
  frontend/src/api/submitReview.ts
  frontend/src/api/togglePostLike.ts
  frontend/src/api/whoami.ts
  frontend/src/models/Post.ts
  frontend/src/routes/accounts/EditAccount.css
  frontend/src/routes/accounts/EditAccount.tsx
  frontend/src/routes/accounts/Login.tsx
  frontend/src/routes/accounts/ProfilePhoto.tsx
  frontend/src/routes/accounts/index.ts
  frontend/src/routes/posts/CreatePost.css
  frontend/src/routes/posts/CreatePost.tsx
  frontend/src/routes/posts/PostPreview.tsx
  frontend/src/routes/posts/ShowPost.css
  frontend/src/routes/posts/ShowPost.tsx
  frontend/src/routes/posts/ViewFeed.tsx
  frontend/src/routes/posts/ViewPost.tsx
  frontend/src/routes/posts/ViewUserFeed.tsx
  frontend/src/routes/posts/comments/ShowComment.tsx
  frontend/src/routes/posts/index.ts
  frontend/src/routes/review/PostReview.css
  frontend/src/routes/review/Review.tsx
  frontend/src/shared/Context.tsx
  frontend/src/shared/ProfilePhoto.css
  frontend/src/shared/ProfilePhoto.tsx
  frontend/src/wrapper/Navbar.tsx
Labels: bug

#96 Uvlačenje odgovora
  frontend/src/routes/posts/ShowPost.tsx
  frontend/src/routes/posts/comments/ShowComment.css
  frontend/src/routes/posts/comments/ShowComment.tsx
Labels: enhancement

#97 Dokumentacija (PR)
  backend/app/controllers/accounts_controller.rb
  backend/app/controllers/application_controller.rb
  backend/app/controllers/comments_controller.rb
  backend/app/controllers/posts_controller.rb
  backend/app/controllers/review_controller.rb
  backend/app/controllers/users_controller.rb
  backend/config/routes.rb
  frontend/src/api/follow.ts
Labels: documentation

#100 Odmagljivanje slika na pregledu objava
  backend/app/models/post.rb
  backend/db/seeds.rb
  frontend/src/models/Post.ts
  frontend/src/routes/posts/ShowPost.tsx
  frontend/src/routes/review/PostReview.tsx
Labels: bug

#99 Popravke praćenja i sviđanja
  frontend/src/routes/posts/ShowPost.tsx
  frontend/src/routes/posts/ViewFeed.tsx
  frontend/src/routes/posts/ViewPost.tsx
Labels: bug

#101 Popravka beskonačnog skrolovanja
  backend/app/controllers/posts_controller.rb
  frontend/src/routes/posts/ViewFeed.tsx
  frontend/src/routes/posts/ViewUserFeed.tsx
Labels: bug

#102 Styling changes and initial code for unlocking.
  frontend/src/App.css
  frontend/src/loader.gif
  frontend/src/logo.png
  frontend/src/routes/accounts/EditAccount.css
  frontend/src/routes/accounts/EditAccount.tsx
  frontend/src/routes/accounts/Login.css
  frontend/src/routes/posts/CreatePost.css
  frontend/src/routes/posts/PostPreview.css
  frontend/src/routes/posts/PostPreview.tsx
  frontend/src/routes/posts/ShowPost.css
  frontend/src/routes/posts/ShowPost.tsx
  frontend/src/routes/posts/ViewFeed.css
  frontend/src/routes/posts/ViewFeed.tsx
  frontend/src/routes/posts/ViewUserFeed.css
  frontend/src/routes/posts/comments/ShowComment.css
  frontend/src/routes/review/PostReview.css
  frontend/src/routes/review/Review.css
  frontend/src/shared/Button.css
  frontend/src/wrapper/Navbar.css
  frontend/src/wrapper/Navbar.tsx
Labels: enhancement

#103 Pretraga i neke ispravke
  backend/app/controllers/posts_controller.rb
  backend/app/controllers/users_controller.rb
  backend/config/routes.rb
  frontend/package.json
  frontend/src/api/index.ts
  frontend/src/api/search.ts
  frontend/src/routes/posts/ShowPost.css
  frontend/src/wrapper/Navbar.css
  frontend/src/wrapper/Navbar.tsx
  frontend/yarn.lock
Labels: bug, enhancement

#104 Improving suggestions
  backend/app/controllers/posts_controller.rb
  frontend/src/index.html
  frontend/src/routes/accounts/FollowSuggestions.css
  frontend/src/routes/posts/ViewFeed.tsx
  frontend/src/routes/posts/ViewUserFeed.tsx
  frontend/src/shared/SubmissionIndicator.css
  frontend/static/favicon.ico
  frontend/static/favicon.png
Labels: enhancement

#106 Postavka za jedinično testiranje
  backend/app/controllers/accounts_controller.rb
  backend/app/controllers/application_controller.rb
  backend/test/controllers/accounts_controller_test.rb
  backend/test/controllers/comments_controller_test.rb
  backend/test/controllers/posts_controller_test.rb
  backend/test/controllers/review_controller_test.rb
  backend/test/controllers/users_controller_test.rb
  backend/test/fixtures/blocks.yml
  backend/test/fixtures/comment_likes.yml
  backend/test/fixtures/comments.yml
  backend/test/fixtures/follows.yml
  backend/test/fixtures/hashtags.yml
  backend/test/fixtures/post_likes.yml
  backend/test/fixtures/posts.yml
  backend/test/fixtures/unlocks.yml
  backend/test/fixtures/users.yml
  backend/test/test_helper.rb
Labels: enhancement

#107 Implement unlocking of the post
  backend/app/controllers/posts_controller.rb
  backend/app/models/post.rb
  backend/config/routes.rb
  frontend/src/api/index.ts
  frontend/src/api/unlockPost.ts
  frontend/src/models/Post.ts
  frontend/src/routes/posts/CreatePost.css
  frontend/src/routes/posts/CreatePost.tsx
  frontend/src/routes/posts/ShowPost.tsx
  frontend/src/routes/posts/ViewFeed.tsx
  frontend/src/routes/posts/ViewPost.tsx
Labels: enhancement

#109 Konačne ispravke
  backend/app/controllers/posts_controller.rb
  backend/app/controllers/users_controller.rb
  backend/app/models/comment.rb
  backend/app/models/post.rb
  backend/app/models/user.rb
  docker-compose.yml
  frontend/src/api/unlockPost.ts
  frontend/src/models/Post.ts
  frontend/src/routes/posts/ShowPost.css
  frontend/src/routes/posts/ShowPost.tsx
  frontend/src/routes/posts/ViewFeed.css
  frontend/src/routes/posts/ViewFeed.tsx
  frontend/src/routes/posts/ViewPost.tsx
  frontend/src/shared/InfiniteScroll.tsx
  frontend/src/wrapper/Navbar.tsx
Labels: bug, enhancement

#108 Testiranje: Pravljenje objave (PR)
  .github/workflows/backend_test.yml
  .github/workflows/integration_test.yml
  backend/app/controllers/posts_controller.rb
  backend/app/controllers/users_controller.rb
  backend/test/controllers/.keep
  backend/test/controllers/posts_controller_test.rb
  backend/test/fixtures/.keep
  backend/test/fixtures/files/.keep
  backend/test/fixtures/files/pfp-invalid-format.png
  backend/test/fixtures/files/pfp-not-tall-enough.jpg
  backend/test/fixtures/files/pfp-not-wide-enough.jpg
  backend/test/fixtures/files/pfp-too-tall.jpg
  backend/test/fixtures/files/pfp-too-wide.jpg
  backend/test/fixtures/files/pfp-valid-high.jpg
  backend/test/fixtures/files/pfp-valid-low.jpg
  backend/test/fixtures/files/pfp-valid.jpg
  backend/test/fixtures/files/post-blur-100.jpg
  backend/test/fixtures/files/post-blur-25.jpg
  backend/test/fixtures/files/post.jpg
  backend/test/test_helper.rb
  docker-compose.yml
  test/.gitignore
  test/jest.config.js
  test/package.json
  test/test/CreatePost.test.ts
  test/test/Login.test.ts
  test/test/utils.ts
  test/tsconfig.json
  test/yarn.lock
Labels: enhancement
